drop DATABASE BMS_DB;
create DATABASE BMS_DB1;

use BMS_DB1;

show databases;

-- STUDENT_PERSONAL_INFO

CREATE TABLE STUDENT_PERSONAL_INFO
(
	STUDENT_ID VARCHAR(5),
    STUDENT_NAME VARCHAR(30),
    DATE_OF_BIRTH DATE,
    GAURDIAN_NAME VARCHAR(30),
    ADDRESS VARCHAR(50),
    CONTACT_NO BIGINT(10),
    MAIL_ID VARCHAR(30),
    GENDER CHAR(1),
    CITIZENSHIP VARCHAR(10),
    CONSTRAINT STUD_PERS_INFO_PK PRIMARY KEY(STUDENT_ID)
);

show tables;

-- STUDENT_REFERENCE_INFO
CREATE TABLE TEACHER_REFERENCE_INFO
(
	STAFF_ID VARCHAR(7),
    TEACHER_NAME VARCHAR(30),
    DATE_OF_BIRTH DATE,
    DEPT_NAME VARCHAR(30),
    ADDRESS VARCHAR(50),
    CONTACT_NO BIGINT(10),
    MAIL_ID VARCHAR(30),
    GENDER CHAR(1),
    CONSTRAINT TEACH_REF_INFO_PK PRIMARY KEY(STAFF_ID),
	CONSTRAINT TEACH_REF_INFO_PK FOREIGN KEY(STAFF_ID) REFERENCES 
);

show tables;

-- ADMIN_REFERENCE_INFO
CREATE TABLE ADMIN_REFERENCE_INFO
(
	ADMIN_ID VARCHAR(7),
    ADMIN_NAME VARCHAR(30),
    DATE_OF_BIRTH DATE,
    DEPT_NAME VARCHAR(30),
    ADDRESS VARCHAR(50),
    CONTACT_NO BIGINT(10),
    MAIL_ID VARCHAR(30),
    GENDER CHAR(1),
    CONSTRAINT ADMIN_REF_INFO_PK PRIMARY KEY(ADMIN_ID),
	CONSTRAINT ADMIN_REF_INFO_PK FOREIGN KEY(ADMIN_ID) REFERENCES 
);

-- COLLEGE_INFO
CREATE TABLE COLLEGE_INFO
(
	IFSC_CODE VARCHAR(15),
    COLLEGE_NAME VARCHAR(30),
    DISTRICT_NAME VARCHAR(30),
    CONSTRAINT COLLEGE_INFO_PK PRIMARY KEY(IFSC_CODE)
);

-- IMPORTANT_INFO
CREATE TABLE IMPORTANT_INFO
(
	LOGIN_ID VARCHAR(7),
    ADMIN_NAME VARCHAR(30),
    DATE_OF_BIRTH DATE,
    REGISTER_DATE DATE,
    ACTIVE_DATE VARCHAR(50),
    OFFICE_NUM VARCHAR(12),
    RECEP_DIGIT DECIMAL(7,2),
    CONSTRAINT IMPORTANT_INFO_PK PRIMARY KEY(LOGIN_ID),
	CONSTRAINT IMPORTANT_INFO_PRIMARY1_FK FOREIGN KEY(STUDENT_ID) REFERENCES(IFSC_CODE)
    CONSTRAINT IMPORTANT_INFO_PRIMARY2_FK FOREIGN KEY(STAFF_ID) REFERENCES(CONTACT_NUM)
);

-- COLLEGE_INFO 
INSERT INTO COLLEGE_INFO(IFSC_CODE, COLLEGE_NAME, DISTRICT_NAME) VALUES('TH7FHR832481HFA0', 'OHLONE','FREMONT');
INSERT INTO COLLEGE_INFO(IFSC_CODE, COLLEGE_NAME, DISTRICT_NAME) VALUES('DT4FHR412434GD10', 'CHABOT','HAYWARD');
INSERT INTO COLLEGE_INFO(IFSC_CODE, COLLEGE_NAME, DISTRICT_NAME) VALUES('FH56NM532481HFA0', 'DEANZA','CUPERTINO');
INSERT INTO COLLEGE_INFO(IFSC_CODE, COLLEGE_NAME, DISTRICT_NAME) VALUES('E47FH5NF567NGFA0', 'EVERGREEN','SAN JOSE');
INSERT INTO COLLEGE_INFO(IFSC_CODE, COLLEGE_NAME, DISTRICT_NAME) VALUES('4HF5RTM8JH81HFA0', 'MISSION','SANTA CLARA');
INSERT INTO COLLEGE_INFO(IFSC_CODE, COLLEGE_NAME, DISTRICT_NAME) VALUES('T65HG87JH909MN30', 'LANEY','OAKLAND');

select * from COLLEGE_INFO;


-- STUDENT_PERSONAL_INFO
INSERT INTO STUDENT_PERSONAL_INFO(STUDENT_ID, STUDENT_NAME, DATE_OF_BIRTH, ADDRESS, CONTACT_NO, MAIL_ID) VALUES('09567483', 'MARQUES','04/18/2000','4564 CHAMBER ST.', '510-516-9026', 'marques.helpingppl@gmail.com');
INSERT INTO STUDENT_PERSONAL_INFO(STUDENT_ID, STUDENT_NAME, DATE_OF_BIRTH, ADDRESS, CONTACT_NO, MAIL_ID) VALUES('04387876', 'TOMMY','05/26/2000','4472 STEVENS CREEK BLVD.', '513-454-7687', 'tommyisking@hotmail.com');
INSERT INTO STUDENT_PERSONAL_INFO(STUDENT_ID, STUDENT_NAME, DATE_OF_BIRTH, ADDRESS, CONTACT_NO, MAIL_ID) VALUES('07854345', 'JOSE','02/13/2000','456 1ST ST.', '897-543-8897', 'joseinhisprime.gt@gmail.com');
INSERT INTO STUDENT_PERSONAL_INFO(STUDENT_ID, STUDENT_NAME, DATE_OF_BIRTH, ADDRESS, CONTACT_NO, MAIL_ID) VALUES('09456382', 'JOSHUA','05/18/2000','345 10TH ST.', '564-565-1545', 'ogjoshhhh@gmail.com');
INSERT INTO STUDENT_PERSONAL_INFO(STUDENT_ID, STUDENT_NAME, DATE_OF_BIRTH, ADDRESS, CONTACT_NO, MAIL_ID) VALUES('05647438', 'ANTHONY','01/19/2000','5667 EAST SANTA CLARA ST.', '576-345-6756', 'anthonyiscool@yahoo.com');

select * from STUDENT_PERSONAL_INFO;








    



    
    
    